### ISSUE TITLE
粒子效果不显示

### ISSUE THREAD

**Issue by yqh708** [vensing/cesium-wind#1]
大佬你好，我用vue-cli搭建的前端项目，引入这个windy.js ，但是粒子效果不显示，也没有报错，拖拽缩放的时候可以看到一些效果，但是线条都是放大的。我用的是cesium1.7

**Comment by vensing** [comment]
> 大佬你好，我用vue-cli搭建的前端项目，引入这个windy.js ，但是粒子效果不显示，也没有报错，拖拽缩放的时候可以看到一些效果，但是线条都是放大的。我用的是cesium1.7

能否提供下你的项目仓库地址呢，或者我有时间再开一个基于 Vue 的 Cesium 风场动画项目。
