### ISSUE TITLE
大佬能解释下json字段含义吗

### ISSUE THREAD

**Issue by QDzzzhy** [vensing/cesium-wind#2]

**Comment by vensing** [comment]
gfs.json 里面的是 GFS 模式下的风场 U/V 网格数据，主要看经纬度范围(lon:0\~359, lat:-90\~90)，dx和dy是网格间距，文件里都是1，也就是每隔1度为一个网格。具体的使用说明见 https://github.com/vensing/cesium-wind/blob/8849725ab6ecad3b5ea7ebe60e549e5595c806e1/Windy.js#L68

**Comment by shy-zhy** [comment]
我在做中国区的风场叠加，目前修改了
numberPoints: 101441,
nx: 361,
ny: 281,
lo1: 60,
la1: -10,
lo2: 150,
la2: 60,
dx: 0.25,
dy: -0.25
这些参数，但是和leaflet叠加的风场不太一致，请问是哪里不对吗

**Comment by vensing** [comment]
> 我在做中国区的风场叠加，目前修改了
> 
> numberPoints: 101441,
> 
> nx: 361,
> 
> ny: 281,
> 
> lo1: 60,
> 
> la1: -10,
> 
> lo2: 150,
> 
> la2: 60,
> 
> dx: 0.25,
> 
> dy: -0.25
> 
> 这些参数，但是和leaflet叠加的风场不太一致，请问是哪里不对吗

dy:0.25，不应该是负的。如果你是想限制风场动画的显示区域，可以在Windy.js 303行 加一个if设置中国区的经纬度范围，λ = coord[0], φ = coord[1]; 这两个变量是经纬度，see: https://github.com/vensing/cesium-wind/blob/8849725ab6ecad3b5ea7ebe60e549e5595c806e1/Windy.js#L303

**Comment by QDzzzhy** [comment]
> > 我在做中国区的风场叠加，目前修改了
> > numberPoints: 101441,
> > nx: 361,
> > ny: 281,
> > lo1: 60,
> > la1: -10,
> > lo2: 150,
> > la2: 60,
> > dx: 0.25,
> > dy: -0.25
> > 这些参数，但是和leaflet叠加的风场不太一致，请问是哪里不对吗
> 
> dy:0.25，不应该是负的。如果你是想限制风场动画的显示区域，可以在Windy.js 303行 加一个if设置中国区的经纬度范围，λ = coord[0], φ = coord[1]; 这两个变量是经纬度，see:
> 
> https://github.com/vensing/cesium-wind/blob/8849725ab6ecad3b5ea7ebe60e549e5595c806e1/Windy.js#L303

设置为0.25会偏离到下面
![image](https://user-images.githubusercontent.com/39055443/92589024-81041500-f2cc-11ea-9516-6ad37673ca96.png)

设置为-0.25是正常的范围
![image](https://user-images.githubusercontent.com/39055443/92589110-a85ae200-f2cc-11ea-9f32-06239e749080.png)
但是对比同样数据的leaflet会不一样
![image](https://user-images.githubusercontent.com/39055443/92589152-ba3c8500-f2cc-11ea-832b-36398d247740.png)
这个leaflet的是和windy.com对比过正确的风场

**Comment by vensing** [comment]
Cesium 你切换到二维模式下，放大到和 leaflet 地图差不多的层级，再对比下看看

**Comment by vensing** [comment]
la1是纬度最大值，la2是纬度最小值；你设置反了，所以dx为正显示不正常。另外返回的json数组第一项是U向风，第二项是V向风，对应好，你修改下再看看呢🥰

**Comment by QDzzzhy** [comment]
抱歉昨天有事没有回复，我刚才试了一下好像确实是的，目前这组数据来看应该是正确了，我再多对比几组数据看看，非常感谢您的指教。

**Comment by vensing** [comment]
Awesome ~ 很高兴能够帮助到你
